CREATE TYPE "public"."booking_source" AS ENUM('WEB', 'SEED');--> statement-breakpoint
CREATE TYPE "public"."booking_status" AS ENUM('CONFIRMED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."fare_brand" AS ENUM('BASIC', 'CLASSIC', 'PREMIUM', 'BUSINESS');--> statement-breakpoint
CREATE TYPE "public"."cabin" AS ENUM('Y', 'W', 'J');--> statement-breakpoint
CREATE TYPE "public"."direction" AS ENUM('OUT', 'RET');--> statement-breakpoint
CREATE TYPE "public"."flight_status" AS ENUM('SCHEDULED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."market" AS ENUM('DOM', 'TB', 'INT');--> statement-breakpoint
CREATE TYPE "public"."pax_type" AS ENUM('ADT', 'CHD', 'INF');--> statement-breakpoint
CREATE TYPE "public"."region" AS ENUM('CA', 'US', 'SUN');--> statement-breakpoint
CREATE TYPE "public"."route_kind" AS ENUM('TRUNK', 'SPOKE');--> statement-breakpoint
CREATE TYPE "public"."trip_type" AS ENUM('OW', 'RT');--> statement-breakpoint
CREATE TABLE "aircraft_cabins" (
	"aircraft_code" text NOT NULL,
	"cabin" "cabin" NOT NULL,
	"seats" smallint NOT NULL,
	"product" text NOT NULL,
	"pitch_in" smallint NOT NULL,
	CONSTRAINT "aircraft_cabins_aircraft_code_cabin_pk" PRIMARY KEY("aircraft_code","cabin")
);
--> statement-breakpoint
CREATE TABLE "aircraft_types" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	"cruise_kmh" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "airports" (
	"iata" char(3) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"city" text NOT NULL,
	"region" "region" NOT NULL,
	"country" char(2) NOT NULL,
	"province" text,
	"tz" text NOT NULL,
	"lat" double precision NOT NULL,
	"lon" double precision NOT NULL,
	"is_hub" boolean DEFAULT false NOT NULL,
	"aif_cents" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "booking_segments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "booking_segments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"booking_id" integer NOT NULL,
	"direction" "direction" NOT NULL,
	"seq" smallint NOT NULL,
	"flight_id" integer NOT NULL,
	"cabin" "cabin" NOT NULL,
	"brand_code" "fare_brand" NOT NULL,
	"rbd" char(1) NOT NULL,
	"seats" smallint NOT NULL,
	"fare_cents" integer NOT NULL,
	CONSTRAINT "booking_segments_booking_id_direction_seq_unique" UNIQUE("booking_id","direction","seq")
);
--> statement-breakpoint
CREATE TABLE "bookings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bookings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pnr" char(6) NOT NULL,
	"status" "booking_status" DEFAULT 'CONFIRMED' NOT NULL,
	"trip_type" "trip_type" NOT NULL,
	"origin" char(3) NOT NULL,
	"destination" char(3) NOT NULL,
	"adults" smallint NOT NULL,
	"children" smallint NOT NULL,
	"infants" smallint NOT NULL,
	"contact_email" text NOT NULL,
	"contact_phone" text NOT NULL,
	"currency" char(3) DEFAULT 'CAD' NOT NULL,
	"base_cents" integer NOT NULL,
	"tax_cents" integer NOT NULL,
	"total_cents" integer NOT NULL,
	"source" "booking_source" NOT NULL,
	"booked_at" timestamp with time zone NOT NULL,
	CONSTRAINT "bookings_pnr_unique" UNIQUE("pnr")
);
--> statement-breakpoint
CREATE TABLE "fare_brands" (
	"code" "fare_brand" PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"cabin" "cabin" NOT NULL,
	"display_order" smallint NOT NULL,
	"tagline" text NOT NULL,
	"bags_included" smallint NOT NULL,
	"seat_selection" text NOT NULL,
	"change_fee_cents" integer,
	"refundable" boolean NOT NULL,
	"fallback_brand" "fare_brand",
	"perks" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fare_buckets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fare_buckets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"brand_code" "fare_brand" NOT NULL,
	"rbd" char(1) NOT NULL,
	"step" smallint NOT NULL,
	"lf_max" numeric(4, 3) NOT NULL,
	"min_adv_days" smallint NOT NULL,
	"multiplier" numeric(5, 3) NOT NULL,
	CONSTRAINT "fare_buckets_brand_code_rbd_unique" UNIQUE("brand_code","rbd")
);
--> statement-breakpoint
CREATE TABLE "flight_cabin_inventory" (
	"flight_id" integer NOT NULL,
	"cabin" "cabin" NOT NULL,
	"capacity" smallint NOT NULL,
	"sold" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "flight_cabin_inventory_flight_id_cabin_pk" PRIMARY KEY("flight_id","cabin"),
	CONSTRAINT "inventory_sold_range" CHECK ("flight_cabin_inventory"."sold" >= 0 AND "flight_cabin_inventory"."sold" <= "flight_cabin_inventory"."capacity")
);
--> statement-breakpoint
CREATE TABLE "flight_schedules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flight_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"flight_number" integer NOT NULL,
	"route_id" integer NOT NULL,
	"aircraft_code" text NOT NULL,
	"dep_local_time" text NOT NULL,
	"block_min" smallint NOT NULL,
	"dow_mask" smallint NOT NULL,
	"effective_from" date NOT NULL,
	"effective_to" date NOT NULL,
	"bank_tag" text,
	CONSTRAINT "flight_schedules_flight_number_effective_from_unique" UNIQUE("flight_number","effective_from")
);
--> statement-breakpoint
CREATE TABLE "flights" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"schedule_id" integer NOT NULL,
	"flight_number" integer NOT NULL,
	"route_id" integer NOT NULL,
	"origin" char(3) NOT NULL,
	"dest" char(3) NOT NULL,
	"aircraft_code" text NOT NULL,
	"dep_local_date" date NOT NULL,
	"dep_utc" timestamp with time zone NOT NULL,
	"arr_utc" timestamp with time zone NOT NULL,
	"block_min" smallint NOT NULL,
	"status" "flight_status" DEFAULT 'SCHEDULED' NOT NULL,
	CONSTRAINT "flights_flight_number_dep_local_date_unique" UNIQUE("flight_number","dep_local_date")
);
--> statement-breakpoint
CREATE TABLE "passengers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "passengers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"booking_id" integer NOT NULL,
	"seq" smallint NOT NULL,
	"type" "pax_type" NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"dob" date NOT NULL,
	"infant_of_seq" smallint
);
--> statement-breakpoint
CREATE TABLE "routes" (
	"id" integer PRIMARY KEY NOT NULL,
	"origin" char(3) NOT NULL,
	"dest" char(3) NOT NULL,
	"distance_km" integer NOT NULL,
	"market" "market" NOT NULL,
	"kind" "route_kind" NOT NULL,
	CONSTRAINT "routes_origin_dest_unique" UNIQUE("origin","dest")
);
--> statement-breakpoint
CREATE TABLE "seed_state" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "aircraft_cabins" ADD CONSTRAINT "aircraft_cabins_aircraft_code_aircraft_types_code_fk" FOREIGN KEY ("aircraft_code") REFERENCES "public"."aircraft_types"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "booking_segments" ADD CONSTRAINT "booking_segments_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "booking_segments" ADD CONSTRAINT "booking_segments_flight_id_flights_id_fk" FOREIGN KEY ("flight_id") REFERENCES "public"."flights"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fare_buckets" ADD CONSTRAINT "fare_buckets_brand_code_fare_brands_code_fk" FOREIGN KEY ("brand_code") REFERENCES "public"."fare_brands"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flight_cabin_inventory" ADD CONSTRAINT "flight_cabin_inventory_flight_id_flights_id_fk" FOREIGN KEY ("flight_id") REFERENCES "public"."flights"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flight_schedules" ADD CONSTRAINT "flight_schedules_route_id_routes_id_fk" FOREIGN KEY ("route_id") REFERENCES "public"."routes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flight_schedules" ADD CONSTRAINT "flight_schedules_aircraft_code_aircraft_types_code_fk" FOREIGN KEY ("aircraft_code") REFERENCES "public"."aircraft_types"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flights" ADD CONSTRAINT "flights_schedule_id_flight_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."flight_schedules"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flights" ADD CONSTRAINT "flights_route_id_routes_id_fk" FOREIGN KEY ("route_id") REFERENCES "public"."routes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passengers" ADD CONSTRAINT "passengers_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "routes" ADD CONSTRAINT "routes_origin_airports_iata_fk" FOREIGN KEY ("origin") REFERENCES "public"."airports"("iata") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "routes" ADD CONSTRAINT "routes_dest_airports_iata_fk" FOREIGN KEY ("dest") REFERENCES "public"."airports"("iata") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "booking_segments_flight_idx" ON "booking_segments" USING btree ("flight_id");--> statement-breakpoint
CREATE INDEX "bookings_booked_at_idx" ON "bookings" USING btree ("booked_at");--> statement-breakpoint
CREATE INDEX "bookings_source_idx" ON "bookings" USING btree ("source");--> statement-breakpoint
CREATE INDEX "flights_route_dep_idx" ON "flights" USING btree ("route_id","dep_utc");--> statement-breakpoint
CREATE INDEX "flights_origin_date_idx" ON "flights" USING btree ("origin","dep_local_date");--> statement-breakpoint
CREATE INDEX "flights_dep_idx" ON "flights" USING btree ("dep_utc");--> statement-breakpoint
CREATE INDEX "passengers_booking_idx" ON "passengers" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "passengers_last_name_idx" ON "passengers" USING btree ("last_name");